---
title: "Latihan 4"
author: "Cut Ashifa Sawallida"
date: "2025-09-17"
output: html_document
---

Proses MA(2)

Proses MA(2) dapat dituliskan sebagai berikut:

$$
Y_{t} = c + e_t + \theta_{1}e_{t-1} + \theta_{2}e_{t-2}
$$

Terlihat bahwa $e_t$, atau white noise, berperan penting dalam pembangkitan proses MA. $\theta$ ditentukan oleh kita sendiri

1. Pembangkitan Model MA(2)

Akan dicoba membangkitkan proses MA(2) dengan $\theta_1 = 0.4$ dan $\theta_2 = 0.6$ sebanyak 300 observasi dan $c=0$. Karena diperlukan satu nilai awal untuk $e_{t-1}$, masukkan nilai pertama white noise sebagai nilai awal tersebut.

{r}
set.seed(1084)
wn <- rnorm(300)
ma2 <- wn[c(1,2)]
ts.plot(wn)

Nilai-nilai selanjutnya dapat dicari melalui loop. Bentuk loop dapat dilihat dari rumus MA(2) yang hendak dibangkitkan:

$$
Y_t = e_t - 0.4e_{t-1} - 0.6e_{t-2}
$$

{r}
set.seed(1084)
for(i in 3:300){
   ma2[i] <- wn[i] - 0.4 * wn[i - 1] - 0.6 * wn[i - 2]
}
head(ma2)

Didapat sebanyak 300 nilai MA. Selain menggunakan cara di atas, pembangkitan proses MA(2) dapat dilakukan dengan fungsi arima.sim() sebagai berikut.

{r}
ma.2 <- arima.sim(list(order=c(0,0,2), ma=c(0.4, 0.6)), n=300)  
head(ma.2)

2. Karakteristik MA(2)

a. Plot Time Series

{r}
ts.plot(ma2)

Berdasarkan plot time series, terlihat bahwa data MA(2) yang dibangkitkan stasioner dalam rataan

b. Plot ACF

{r}
acf(ma2,lag.max = 20)

Berdasarkan plot ACF tersebut, terlihat bahwa plot ACF cuts off. Data yang kita miliki dapat dikatakan stasioner.

c. Plot PACF

{r}
pacf(ma2)

Berdasarkan plot PACF tersebut, terlihat bahwa plot PACF cenderung tails off dan membentuk gelombang sinus. Data yang kita miliki dapat dikatakan stasioner.

d. Plot EACF

{r}
TSA::eacf(ma2)

Berdasarkan pola segitiga nol pada plot EACF, terlihat bahwa segitiga nol berada pada ordo AR(0) dan ordo MA(2). Data yang kita miliki dapat dikatakan stasioner.

3. Scatterplot Antar Lag & Autokorelasi Peubah

a. Korelasi antara $Y_t$ dengan $Y_{t-1}$

{r}
#Yt
yt_ma2 <- ma2[-1]
#Yt-1
yt_1_ma2 <- ma2[-300]

plot(x = yt_1_ma2, y = yt_ma2,
     xlab = expression(Y[t-1]), ylab = expression(Y[t]),
     main = "Scatterplot Yt vs Yt-1")

Berdasarkan scatterplot tersebut, terlihat bahwa terdapat hubungan negatif antara $Y_t$ dengan $Y_{t-1}$. Hal ini sesuai dengan teori yang ada

{r}
cor(yt_ma2,yt_1_ma2)

Korelasi antara $Y_t$ dengan $Y_{t-1}$ dari hasil simulasi mendekati perhitungan teoritis yaitu

$$
\rho_1 = \frac{-\theta_1 + \theta_1 \theta_2}{1 + \theta_1^2 + \theta_2^2} = \frac{-0.4 + (0.4)(0.6)  }{1 + 0.4^2 + 0.6^2} =-0.105
$$

b. Korelasi antara $Y_t$ dengan $Y_{t-2}$

{r}
#Yt
yt_ma2 <- ma2[-c(1,2)]
#Yt-2
yt_2_ma2 <- ma2[-c(199,200)]

plot(x = yt_2_ma2, y = yt_ma2,
     xlab = expression(Y[t-2]), ylab = expression(Y[t]),
     main = "Scatterplot Yt vs Yt-2")

Berdasarkan scatterplot tersebut, terlihat bahwa terdapat hubungan negatif antara $Y_t$ dengan $Y_{t-2}$. Hal ini sesuai dengan teori yang ada

{r}
cor(yt_ma2,yt_2_ma2)

Korelasi antara $Y_t$ dengan $Y_{t-2}$ hasil simulasi mendekati teori yang ada yaitu

$$
\rho_2 = \frac{-\theta_2}{1 + \theta_1^2 + \theta_2^2} = \frac{-0.6 }{1 + 0.4^2 + 0.6^2} =-0.395
$$

c. Korelasi antara $Y_t$ dengan $Y_{t-3}$

{r}
yt_ma2   <- ma2[-c(1,2,3)]
yt_3_ma2 <- ma2[-c(298,299,300)]
plot(x = yt_3_ma2, y = yt_ma2,
     xlab = expression(Y[t-3]), ylab = expression(Y[t]),
     main = "Scatterplot Yt vs Yt-3")

Berdasarkan scatterplot tersebut, terlihat bahwa cenderung tidak terdapat hubungan antara $Y_t$ dengan $Y_{t-3}$.

{r}
cor(yt_ma2,yt_3_ma2)

Korelasi antara $Y_t$ dengan $Y_{t-3}$ hasil simulasi mendekati teori yang ada yaitu 0.

Proses AR(2)

Proses AR(2) dapat dituliskan sebagai berikut:

$$ Y_{t} = c + e_t + \phi_{1}Y_{t-1} + \phi_{2}Y_{t-2} $$ Terlihat bahwa $Y_t$ berperan penting dalam pembangkitan proses AR.

1. Pembangkitan Model AR(2)

Akan dicoba membangkitkan proses AR paling sederhana, yaitu AR(1) dengan $\phi_1 = 0.5$ dan $\phi = 0.2$ sebanyak 300 observasi dan $c=0$.

{r}
set.seed(1084)

Nilai-nilai selanjutnya dapat dicari melalui loop. Bentuk loop dapat dilihat dari rumus AR(2) yang hendak dibangkitkan:

$$ Y_t = e_t + 0.5Y_{t-1} + 0.2Y_{t-2} $$

{r}
n <- 300
ar2 <- rep(0, n) # vektor kosong
ar2[1] <- wn[1]
ar2[2] <- 0.5*ar2[1] + wn[2]

for (i in 3:n) {
  ar2[i] <- wn[i] + 0.5*ar2[i-1] + 0.2*ar2[i-2]
}

head(ar2)

Selain menggunakan cara di atas, pembangkitan proses AR dapat dilakukan dengan fungsi arima.sim() sebagai berikut.

{r}
ar.2 <- arima.sim(list(order=c(2,0,0), ar=c(0.5, 0.2)), n=300)
head(ar.2)

2. Karakteristik AR(2)

a. Plot Time Series

{r}
ts.plot(ar2)

Berdasarkan plot time series tersebut terlihat bahwa data cenderung stasioner pada rataan.

b. Plot ACF

{r}
acf(ar2, main="ACF dari AR(2)")

Berdasarkan plot ACF tersebut terlihat bahwa plot ACF cenderung tails off dan cenderung membentuk pola grafik sinus

c. Plot PACF

{r}
pacf(ar2, main="PACF dari AR(2)")

Berdasarkan plot PACF tersebut, terlihat bahwa plot PACF cuts off pada lag kedua, sejalan dengan teori yang ada.

d. Plot EACF

{r}
TSA::eacf(ar2)

Berdasarkan pola segitiga nol pada plot EACF, terlihat bahwa segitiga nol berada pada ordo AR(2) dan ordo MA(0)

3. Scatterplot Antar Lag & Autokorelasi Peubah

a. Korelasi antara $Y_t$ dengan $Y_{t-1}$

{r}
#Yt
yt_ar2 <- ar2[-1]
#Yt-1
yt_1_ar2 <- ar2[-300]

plot(x = yt_1_ar2, y = yt_ar2,
     xlab = expression(Y[t-1]), ylab = expression(Y[t]),
     main = "Scatterplot Yt vs Yt-1")

Berdasarkan scatterplot tersebut, terlihat bahwa terdapat hubungan positif antara $Y_t$ dengan $Y_{t-1}$. Hal ini sesuai dengan teori yang ada

{r}
cor(yt_ar2,yt_1_ar2)

Korelasi antara $Y_t$ dengan $Y_{t-1}$ dari hasil simulasi mendekati perhitungan teoritis yaitu

$$
\rho_{1} = \frac{\phi_{1}}{1 - \phi_{2}} = \frac{0.5}{1 - 0.2} = 0.625
$$

b. Korelasi antara $Y_t$ dengan $Y_{t-2}$

{r}
#Yt
yt_ar2 <- ar2[-c(1,2)]
#Yt-2
yt_2_ar2 <- ar2[-c(199,200)]

plot(x = yt_2_ar2, y = yt_ar2,
     xlab = expression(Y[t-2]), ylab = expression(Y[t]),
     main = "Scatterplot Yt vs Yt-2")

Berdasarkan scatterplot tersebut, terlihat bahwa terdapat hubungan positif antara $Y_t$ dengan $Y_{t-2}$. Hal ini sesuai dengan teori yang ada

{r}
cor(yt_ar2,yt_2_ar2)

Korelasi antara $Y_t$ dengan $Y_{t-2}$ dari hasil simulasi mendekati perhitungan teoritis yaitu

$$
\rho_{2} = \frac{\phi_{2}(1 - \phi_{2}) + \phi_{1}^{2}}{1 - \phi_{2}} = \frac{0.2(1 - 0.2) + 0.5^{2}}{1 - 0.2} = 0.5125
$$

c. Korelasi antara $Y_t$ dengan $Y_{t-3}$

{r}
yt_ar2   <- ar2[-c(1,2,3)]
yt_3_ar2 <- ar2[-c(298,299,300)]
plot(x = yt_3_ar2, y = yt_ar2,
     xlab = expression(Y[t-3]), ylab = expression(Y[t]),
     main = "Scatterplot Yt vs Yt-3")

Berdasarkan scatterplot tersebut, terlihat bahwa terdapat hubungan positif yang lemah antara $Y_t$ dengan $Y_{t-3}$. Hal ini sesuai dengan teori yang ada

{r}
cor(yt_ar2,yt_3_ar2)

Korelasi antara $Y_t$ dengan $Y_{t-3}$ dari hasil simulasi mendekati perhitungan teoritis yaitu

$$
\rho_{3} = \phi_{1}\rho_{2} + \phi_{2}\rho_{1} = (0.5)(0.5125) + (0.2)(0.625) = 0.38125
$$

Proses ARMA(2,2)

Bentuk umum data berpola ARMA.

$$
Y_{t} = c + \sum_{i=1}^p \phi_{i}y_{t-i} + \sum_{j=1}^q e_{t-j}+ e_{t}
$$

1. Pembangkitan Model ARMA(2,2)

{r}
set.seed(1084)
ma2 <- arma.sim(300, c(0.4, 0.6), 0)
ar2 <- arma.sim(300, 0, c(0.5, 0.2))

par(mfrow = c(2, 2))
acf(ma2)
pacf(ma2)
acf(ar2)
pacf(ar2)

{r}
set.seed(1084)
n = 300
phi1 = 0.5
phi2 = 0.2
theta1 = 0.4
theta2 = 0.6

y.arma=c(1:n)
for (i in 3:n){y.arma[i] = phi1*y.arma[i-1] + theta1*wn[i-1] + phi2*y.arma[i-2] + theta2*wn[i-2]+wn[i]}
head(y.arma)

Pembangkitan ARMA(p,q) juga dapat dilakukan dengan fungsi arima.sim sebagai berikut.

{r}
set.seed(1084)
arma22 <- arima.sim(list(order=c(2,0,2), ar = c(0.5, 0.2), ma = c(0.4, 0.6)), n=300)
head(arma22)

2. Karakteristik ARMA(2,2)

a. Plot Time Series

{r}
par(mfrow = c(1, 2))
ts.plot(y.arma)
ts.plot(arma22)
par(mfrow = c(1, 1))

Berdasarkan plot time series tersebut, terlihat bahwa model ARMA(2,2) cenderung stasioner dalam rataan

b. Plot ACF

{r}
par(mfrow = c(1, 2))
acf(y.arma)
acf(arma22)
par(mfrow = c(1, 1))

Berdasarkan plot ACF tersebut, terlihat bahwa model ARMA(2,2) hasil simulasi memiliki plot ACF yang tails off, sesuai dengan teori yang ada

c. Plot PACF

{r}
par(mfrow = c(1, 2))
ts.plot(y.arma)
ts.plot(arma22)
par(mfrow = c(1, 1))

Berdasarkan plot PACF tersebut, terlihat bahwa model ARMA(2,2) hasil simulasi memiliki plot PACF yang tails off, sesuai dengan teori

d. Plot EACF

{r}
TSA::eacf(y.arma)
TSA::eacf(arma22)

Berdasarkan pola segitiga nol pada plot EACF, terlihat bahwa segitiga nol berada pada ordo AR(2) dan ordo MA(2)

3. Scatterplot Antar Lag & Autokorelasi Peubah

{r}
# Menyusun matriks parameter
# Parameter (ubah sesuai modelmu)
phi1 <- 0.5
phi2 <- 0.2
theta1 <- 0.4
theta2 <- 0.6
sigma2 <- 1

# Vektor b (k=0..3)
b0 <- sigma2*(1 + theta1^2 + theta2^2)
b1 <- sigma2*(theta1 + theta1*theta2)
b2 <- sigma2*(theta2)
b3 <- 0
b <- c(b0, b1, b2, b3)

# Matriks A (4x4) sesuai persamaan
A <- matrix(c(
  1,     -phi1, -phi2,  0,
 -phi1, 1-phi2,   0,    0,
 -phi2,  -phi1,   1,    0,
  0,     -phi2,  -phi1, 1
), nrow=4, byrow=TRUE)

# Selesaikan sistem linear
gamma <- solve(A, b)  

a. Korelasi antara $Y_t$ dengan $Y_{t-1}$

{r}
#Yt
yt_arma22 <- arma22[-1]
#Yt-1
yt_1_arma22 <- arma22[-300]

plot(x = yt_1_arma22, y = yt_arma22,
     xlab = expression(Y[t-1]), ylab = expression(Y[t]),
     main = "Scatterplot Yt vs Yt-1")

Berdasarkan scatterplot tersebut, terlihat bahwa terdapat hubungan positif antara $Y_t$ dengan $Y_{t-1}$. Hal ini sesuai dengan teori yang ada

{r}
cor(yt_arma22,yt_1_arma22)

Korelasi antara $Y_t$ dengan $Y_{t-1}$ dari hasil simulasi mendekati perhitungan teoritis.

{r}
rho1 <- gamma[2]/gamma[1]
rho1

b. Korelasi antara $Y_t$ dengan $Y_{t-2}$

{r} 
#Yt 
yt_arma22 <- arma22[-c(1,2)] 
#Yt-2 
yt_2_arma22 <- arma22[-c(199,200)]  

plot(x = yt_2_arma22, y = yt_arma22,      
     xlab = expression(Y[t-2]), ylab = expression(Y[t]),      main = "Scatterplot Yt vs Yt-2")

Berdasarkan scatterplot tersebut, terlihat bahwa terdapat hubungan positif antara $Y_t$ dengan $Y_{t-2}$. Hal ini sesuai dengan teori yang ada

{r} 
cor(yt_arma22,yt_2_arma22)

Korelasi antara $Y_t$ dengan $Y_{t-2}$ dari hasil simulasi mendekati perhitungan teoritis yaitu

{r}
rho2 <- gamma[3]/gamma[1]
rho2

c. Korelasi antara $Y_t$ dengan $Y_{t-3}$

{r} 
#Yt 
yt_arma22 <- arma22[-c(1,2,3)] 
#Yt-3
yt_3_arma22 <- arma22[-c(298,299,300)] 

plot(x = yt_3_arma22, y = yt_arma22,      
     xlab = expression(Y[t-3]), ylab = expression(Y[t]),      main = "Scatterplot Yt vs Yt-3")

Berdasarkan scatterplot tersebut, terlihat bahwa terdapat hubungan positif yang antara $Y_t$ dengan $Y_{t-3}$. Hal ini sesuai dengan teori yang ada

{r} 
cor(yt_arma22,yt_3_arma22)

Korelasi antara $Y_t$ dengan $Y_{t-3}$ dari hasil simulasi mendekati perhitungan teoritis yaitu

{r}
rho3 <- gamma[4]/gamma[1]
rho3

